server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: # your id
            clientSecret: # your secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/hong_talk
    username: root
    password: 1234
    initialization-mode: always