server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /static/** # 2. 이렇게 접근할 수 있게 하겠다.
  resoruces:
    static-locations: classpath:/static/ # 1. 여기에 경로를
    add-mapping: true

  security:
    user:
      name: hong
      password: 1
      roles: USER

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl : false
    hibernate:
      ddl-auto: create-drop
      # none : ddl을 실행 안 함
      # create : drop 후 create
      # create-drop : create 후 종료 시 drop
      # update : 실제 스키마와 비교하여 변경된 부분만 반영
      # validate : 단순 비교작업만 하고 Entity와 실제 스키마가 다르면 오류를 발생시킴

  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: 1234
    initialization-mode: always

logging:
  level:
    root: info
  file:
    name: C:/Users/82108/Desktop/security-log/log.log